//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : AICloud
	/// Data Source    : .\MSSQLSERVER2017
	/// Server Version : 14.00.3192
	/// </summary>
	public partial class AICloudDB : LinqToDB.Data.DataConnection
	{
		public ITable<Airport>     Airports     { get { return this.GetTable<Airport>(); } }
		public ITable<AppLocation> AppLocations { get { return this.GetTable<AppLocation>(); } }
		public ITable<RailWay>     RailWays     { get { return this.GetTable<RailWay>(); } }

		public AICloudDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AICloudDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Airports")]
	public partial class Airport
	{
		[Column, Nullable] public int?   AirportID          { get; set; } // int
		[Column, Nullable] public string Name               { get; set; } // nvarchar(100)
		[Column, Nullable] public string City               { get; set; } // nvarchar(50)
		[Column, Nullable] public string Country            { get; set; } // nvarchar(50)
		[Column, Nullable] public string IATA               { get; set; } // nvarchar(50)
		[Column, Nullable] public string ICAO               { get; set; } // nvarchar(50)
		[Column, Nullable] public string Latitude           { get; set; } // nvarchar(50)
		[Column, Nullable] public string Longitude          { get; set; } // nvarchar(50)
		[Column, Nullable] public string Altitude           { get; set; } // nvarchar(50)
		[Column, Nullable] public string Timezone           { get; set; } // nvarchar(50)
		[Column, Nullable] public string DST                { get; set; } // nvarchar(50)
		[Column, Nullable] public string Tzdatabasetimezone { get; set; } // nvarchar(50)
		[Column, Nullable] public string Type               { get; set; } // nvarchar(50)
		[Column, Nullable] public string Source             { get; set; } // nvarchar(50)
	}

	[Table(Schema="dbo", Name="App_Locations")]
	public partial class AppLocation
	{
		[Column, NotNull    ] public int     LocationID          { get; set; } // int
		[Column,    Nullable] public string  CityName            { get; set; } // varchar(200)
		[Column,    Nullable] public string  LocationName        { get; set; } // varchar(200)
		[Column,    Nullable] public string  ChineseLocationName { get; set; } // nvarchar(200)
		[Column,    Nullable] public string  LocationStatus      { get; set; } // nvarchar(200)
		[Column,    Nullable] public double? Latitude            { get; set; } // float
		[Column,    Nullable] public double? Longitude           { get; set; } // float
		[Column,    Nullable] public int?    LocationTypeID      { get; set; } // int
	}

	[Table(Schema="dbo", Name="RailWays")]
	public partial class RailWay
	{
		[Column("id"), Identity] public int    Id           { get; set; } // int
		[Column(),     Nullable] public string Name         { get; set; } // varchar(120)
		[Column(),     Nullable] public string StartAddress { get; set; } // varchar(200)
		[Column(),     Nullable] public string EndAddress   { get; set; } // varchar(200)
	}
}

#pragma warning restore 1591
